DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS SHIPPING_DETAIL;
DROP TABLE IF EXISTS CART_ITEM;
DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS ADDRESS;

-- CREATE TABLE customers (
--     ID VARCHAR(25),
--     CUST_NAME VARCHAR(50),
--     address VARCHAR(250),
--     noOfOrdersMade INT,
--     PRIMARY KEY (ID)
-- );

CREATE TABLE PRODUCTS (
	ID VARCHAR(25),
	PROD_NAME VARCHAR(50),
	DESCRIPTION VARCHAR(250),
	UNIT_PRICE DECIMAL,
	MANUFACTURER VARCHAR(50),
	CATEGORY VARCHAR(50),
	PROD_CONDITION VARCHAR(50),
	UNITS_IN_STOCK BIGINT,
	UNITS_IN_ORDER BIGINT,
	DISCONTINUED BOOLEAN,
    PRIMARY KEY(ID)
);

CREATE TABLE CART (
	ID VARCHAR(50),
    PRIMARY KEY (ID)
);

CREATE TABLE CART_ITEM (
	ID VARCHAR(75),
	PRODUCT_ID VARCHAR(25),
	CART_ID varchar(50),
	QUANTITY BIGINT,
    PRIMARY KEY(ID),	
    CONSTRAINT product_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
    CONSTRAINT item_cart_FK FOREIGN KEY (CART_ID) REFERENCES CART(ID)
);

CREATE TABLE ADDRESS (
	ID INTEGER AUTO_INCREMENT,
ZIPCODE VARCHAR(25),
	WIDECIDO VARCHAR(25),
	CIGOONGU VARCHAR(25),
	STREETNAME VARCHAR(25),
	BUILDINGNO VARCHAR(25),
	UNITNO VARCHAR(25),
    PRIMARY KEY(ID)
);

CREATE TABLE CUSTOMERS (
	ID INTEGER AUTO_INCREMENT,
	NAME VARCHAR(25),
	PHONE_NUMBER VARCHAR(25),
	BILLING_ADDRESS_ID INTEGER,
    PRIMARY KEY(ID),
	CONSTRAINT address_FK FOREIGN KEY (BILLING_ADDRESS_ID) REFERENCES ADDRESS(ID)
);

CREATE TABLE SHIPPING_DETAIL (
	ID INTEGER AUTO_INCREMENT,
	NAME VARCHAR(25),
	SHIPPING_DATE VARCHAR(25),
	SHIPPING_ADDRESS_ID INTEGER,
	PRIMARY KEY (ID),
	CONSTRAINT  shcustomersip_addr_ID_FK FOREIGN KEY (SHIPPING_ADDRESS_ID) REFERENCES ADDRESS(ID)
);

CREATE TABLE ORDERS (
	ID INTEGER AUTO_INCREMENT,
	CART_ID VARCHAR(50),
	CUSTOMER_ID INTEGER,
	SHIPPING_DETAIL_ID INTEGER,
    PRIMARY KEY (ID),
	CONSTRAINT order_cart_FK FOREIGN KEY (CART_ID) REFERENCES CART(ID),
	CONSTRAINT customer_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
	CONSTRAINT ship_detail_FK FOREIGN KEY (SHIPPING_DETAIL_ID) REFERENCES SHIPPING_DETAIL(ID)
);
ALTER TABLE ORDERS AUTO_INCREMENT=1000;
    
